name: Build & Push (backend)

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types: [completed]

# prevent overlapping runs per ref
concurrency:
  group: backend-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

env:
  IMAGE: gorm2303/firecasting-api

jobs:
  build:
    # only proceed if CI succeeded and the branch is main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the same commit that CI built
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Compute short SHA
        id: vars
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: QEMU
        uses: docker/setup-qemu-action@v3

      - name: Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (multi-arch)
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:sha-${{ steps.vars.outputs.SHORT_SHA }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend
